### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by QuantumHive** [NinjaVault/NinjaHive#15]
- [x] Prevent CSRF for Category _POST_ requests
- [x] SubCategory edit
- [x] MainCategory edit (see 4a45f794d90aca5e25b38cc34cdc955909512a7e)
- [x] Show modal dialog message with linked game items to category on invalid deletion (depends on issue #10)
